eureka:
  server:
    renewal-percent-threshold: 0.9
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 40000
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.wb-parking:${server.port}/eureka/,http://eureka-1.eureka.wb-parking:${server.port}/eureka/,http://eureka-2.eureka.wb-parking:${server.port}/eureka/
    fetch-registry: true
